# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-09 00:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lighten', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lighten',
            name='username',
            field=models.CharField(max_length=20),
        ),
    ]
